# Site Settings
locale                   : "en-US"
title                    : "Itai Shapira"
title_separator          : "–"
name                     : &name "Itai Shapira"
description              : &description "PhD researcher at Harvard working on pluralistic AI alignment, algorithmic social choice and optimization. Publications, code, and projects."
url                      : https://www.itai-shapira.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "ishapira1/ishapira1.github.io"
breadcrumbs              : true # true, false (default)
words_per_minute         : 160
future                   : false
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "IShapira1"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image : "/images/id_2024_black.jpeg"

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : Itai Shapira # If the user or organization name differs from the site's name
  links:
    - "https://scholar.google.com/citations?user=JOQXRbIAAAAJ"
    - "https://www.linkedin.com/in/itai-shapira-54583a2ab"
    - "https://x.com/IShapira1"


# Analytics
analytics:
  provider               : "custom" # Use "google" for Google Analytics 4 (GA4)
  google:
    tracking_id          : "G-W8TFZFL8JH" # Replace with your actual GA4 Measurement ID



# Site Author
author:
  name             : "Itai Shapira"
  avatar           : "id_2024_black.jpeg"
  bio              : "PhD Candidate in Computer Science at Harvard University"
  location         :
  employer         : "Harvard University"
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=JOQXRbIAAAAJ&hl=en&oi=ao"
  email            : "itaishapira@g.harvard.edu"
  researchgate     :
  uri              : "https://www.itai-shapira.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ishapira1"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "itai-shapira-54583a2ab"
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .git
  - .idea
  - .jekyll-assets-cache
  - .sass-cache
  - _site
  - CHANGELOG
  - CHANGELOG.md
  - Capfile
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - README.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - markdown_generator
  - node_modules
  - notebook.py
  - package.json
  - scripts
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
